apiVersion: v1 
kind: ConfigMap 
metadata:
  name: index-html-cm 
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Dev Environment</title></head>
    <body><h1>Это среда разработки</h1></body></html>
