apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base

#patchesStrategicMerge:
#  - patch.yaml
#  - configmap-patch.yaml

namePrefix: prod-

configMapGenerator:
  - name: index-html-cm
    files:
      - index.html=../../overlays/prod/index.html

